// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_timeLBL;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_humLBL;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_updLBL;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_batLBL;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_tmpLBL;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_150522586);    // assets\png.monster-411.png
LV_IMG_DECLARE(ui_img_371709059);    // assets\Custom-Icon-Design-Pretty-Office-9-Battery-3.32.png
LV_IMG_DECLARE(ui_img_1438100199);    // assets\Custom-Icon-Design-Pretty-Office-9-Battery-3.16.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
