// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_timeLBL = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_humLBL = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_updLBL = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_batLBL = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_tmpLBL = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLBL, -32);
    lv_obj_set_y(ui_timeLBL, -137);
    lv_obj_set_align(ui_timeLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLBL, "R2D2");
    lv_obj_set_style_text_font(ui_timeLBL, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -54);
    lv_obj_set_y(ui_Label2, 141);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "");

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_981657527);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 140
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 185
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -19);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 64);
    lv_obj_set_height(ui_Panel2, 54);
    lv_obj_set_x(ui_Panel2, 40);
    lv_obj_set_y(ui_Panel2, 118);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x203460), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -10);
    lv_obj_set_y(ui_Label4, -16);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "HUM");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x83BBCF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humLBL = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_humLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humLBL, -1);
    lv_obj_set_y(ui_humLBL, 12);
    lv_obj_set_align(ui_humLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humLBL, "35.55");
    lv_obj_set_style_text_font(ui_humLBL, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 51);
    lv_obj_set_height(ui_Spinner1, 54);
    lv_obj_set_x(ui_Spinner1, 52);
    lv_obj_set_y(ui_Spinner1, -123);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xF095A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_updLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_updLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_updLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_updLBL, 50);
    lv_obj_set_y(ui_updLBL, -124);
    lv_obj_set_align(ui_updLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_updLBL, "8");
    lv_obj_set_style_text_font(ui_updLBL, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -37);
    lv_obj_set_y(ui_Label6, -113);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "MONITOR");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x90AEC0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 57);
    lv_obj_set_height(ui_Panel3, 3);
    lv_obj_set_x(ui_Panel3, -38);
    lv_obj_set_y(ui_Panel3, 111);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x031329), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 57);
    lv_obj_set_height(ui_Panel4, 3);
    lv_obj_set_x(ui_Panel4, 41);
    lv_obj_set_y(ui_Panel4, 114);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x031329), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batLBL, LV_SIZE_CONTENT);   /// -14
    lv_obj_set_height(ui_batLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batLBL, -21);
    lv_obj_set_y(ui_batLBL, 135);
    lv_obj_set_align(ui_batLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batLBL, "3.06");
    lv_obj_set_style_text_color(ui_batLBL, lv_color_hex(0xD9A2A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batLBL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -26);
    lv_obj_set_y(ui_Label1, 80);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "TEMPERATURE");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x93B3C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tmpLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tmpLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tmpLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tmpLBL, 13);
    lv_obj_set_y(ui_tmpLBL, 251);
    lv_label_set_text(ui_tmpLBL, "22.50");
    lv_obj_set_style_text_font(ui_tmpLBL, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_470678326);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image4, -59);
    lv_obj_set_y(ui_Image4, 134);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 51);
    lv_obj_set_y(ui_Label10, -90);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "updating\n....");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 56);
    lv_obj_set_y(ui_Label11, -67);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "0x34\n0xFA");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x3C4147), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 63);
    lv_obj_set_y(ui_Label12, 103);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "%");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 1);
    lv_obj_set_y(ui_Label3, 136);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "V");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x625D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 67);
    lv_obj_set_height(ui_Panel1, 1);
    lv_obj_set_x(ui_Panel1, -40);
    lv_obj_set_y(ui_Panel1, 91);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x575E6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_timeLBL = NULL;
    ui_Label2 = NULL;
    ui_Image2 = NULL;
    ui_Panel2 = NULL;
    ui_Label4 = NULL;
    ui_humLBL = NULL;
    ui_Spinner1 = NULL;
    ui_updLBL = NULL;
    ui_Label6 = NULL;
    ui_Panel3 = NULL;
    ui_Panel4 = NULL;
    ui_batLBL = NULL;
    ui_Label1 = NULL;
    ui_tmpLBL = NULL;
    ui_Image4 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label3 = NULL;
    ui_Panel1 = NULL;

}
