// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Spinner2;
extern lv_obj_t *ui_timeLBL;
extern lv_obj_t *ui_dateLBL;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_secLBL;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_ioLBL;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_yearLBL;
extern lv_obj_t *ui_dayPNL;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_secHEX;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_img_png);   // assets/img.png
LV_IMG_DECLARE( ui_img_1699707072);   // assets/Designbolts-Free-Valentine-Heart-Heart.16.png


LV_FONT_DECLARE( ui_font_Font1);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
