// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner2 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner2, 98);
lv_obj_set_height( ui_Spinner2, 98);
lv_obj_set_x( ui_Spinner2, 61 );
lv_obj_set_y( ui_Spinner2, 31 );
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Spinner2, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_Spinner2, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Spinner2, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_img_src( ui_Spinner2, &ui_img_img_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

ui_timeLBL = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_timeLBL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeLBL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeLBL, 28 );
lv_obj_set_y( ui_timeLBL, 12 );
lv_label_set_text(ui_timeLBL,"22:45");
lv_obj_set_style_text_font(ui_timeLBL, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dateLBL = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_dateLBL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dateLBL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dateLBL, 28 );
lv_obj_set_y( ui_dateLBL, 62 );
lv_label_set_text(ui_dateLBL,"December 25");
lv_obj_set_style_text_color(ui_dateLBL, lv_color_hex(0xD2D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dateLBL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dateLBL, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_img_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 160
lv_obj_set_x( ui_Image2, -144 );
lv_obj_set_y( ui_Image2, 65 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_secLBL = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_secLBL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_secLBL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_secLBL, 60 );
lv_obj_set_y( ui_secLBL, 32 );
lv_obj_set_align( ui_secLBL, LV_ALIGN_CENTER );
lv_label_set_text(ui_secLBL,"24");
lv_obj_set_style_text_color(ui_secLBL, lv_color_hex(0x41B9DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_secLBL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_secLBL, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 102);
lv_obj_set_height( ui_Panel2, 6);
lv_obj_set_x( ui_Panel2, 62 );
lv_obj_set_y( ui_Panel2, -31 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x4189CA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 89, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 23);
lv_obj_set_height( ui_Panel3, 18);
lv_obj_set_x( ui_Panel3, 138 );
lv_obj_set_y( ui_Panel3, -69 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -1 );
lv_obj_set_y( ui_Label5, 0 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"MO");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 23);
lv_obj_set_height( ui_Panel1, 18);
lv_obj_set_x( ui_Panel1, 138 );
lv_obj_set_y( ui_Panel1, -46 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -1 );
lv_obj_set_y( ui_Label6, 0 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"TU");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel4, 23);
lv_obj_set_height( ui_Panel4, 18);
lv_obj_set_x( ui_Panel4, 138 );
lv_obj_set_y( ui_Panel4, 0 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -1 );
lv_obj_set_y( ui_Label7, 0 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"TH");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel5, 23);
lv_obj_set_height( ui_Panel5, 18);
lv_obj_set_x( ui_Panel5, 138 );
lv_obj_set_y( ui_Panel5, -23 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel5, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -1 );
lv_obj_set_y( ui_Label8, 0 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"WE");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ioLBL = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ioLBL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ioLBL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ioLBL, 172 );
lv_obj_set_y( ui_ioLBL, 33 );
lv_label_set_text(ui_ioLBL,"192.168.2.3");
lv_obj_set_style_text_color(ui_ioLBL, lv_color_hex(0x67B2C0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ioLBL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 172 );
lv_obj_set_y( ui_Label10, 17 );
lv_label_set_text(ui_Label10,"VOLOS CLOCK");
lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xCD25D6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label10, 250, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel7, 23);
lv_obj_set_height( ui_Panel7, 18);
lv_obj_set_x( ui_Panel7, 138 );
lv_obj_set_y( ui_Panel7, 23 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -1 );
lv_obj_set_y( ui_Label11, 0 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"FR");
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel8 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel8, 23);
lv_obj_set_height( ui_Panel8, 18);
lv_obj_set_x( ui_Panel8, 138 );
lv_obj_set_y( ui_Panel8, 46 );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel8, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x9A11A2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -1 );
lv_obj_set_y( ui_Label12, 0 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"SA");
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel9 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel9, 23);
lv_obj_set_height( ui_Panel9, 18);
lv_obj_set_x( ui_Panel9, 138 );
lv_obj_set_y( ui_Panel9, 69 );
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel9, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x9A11A2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -1 );
lv_obj_set_y( ui_Label13, 0 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"SU");
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel6, 65);
lv_obj_set_height( ui_Panel6, 18);
lv_obj_set_x( ui_Panel6, -32 );
lv_obj_set_y( ui_Panel6, 50 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x8E9E1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"VOLOS");

ui_Panel10 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel10, 65);
lv_obj_set_height( ui_Panel10, 18);
lv_obj_set_x( ui_Panel10, -32 );
lv_obj_set_y( ui_Panel10, 72 );
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x8E9E1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel10, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Panel10);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"PROJECTS");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_yearLBL = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_yearLBL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_yearLBL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_yearLBL, -32 );
lv_obj_set_y( ui_yearLBL, 18 );
lv_obj_set_align( ui_yearLBL, LV_ALIGN_CENTER );
lv_label_set_text(ui_yearLBL,"2025");
lv_obj_set_style_text_color(ui_yearLBL, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_yearLBL, 160, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_yearLBL, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dayPNL = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_dayPNL, 6);
lv_obj_set_height( ui_dayPNL, 18);
lv_obj_set_x( ui_dayPNL, 122 );
lv_obj_set_y( ui_dayPNL, -69 );
lv_obj_set_align( ui_dayPNL, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_dayPNL, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_dayPNL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_dayPNL, lv_color_hex(0x96AA10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dayPNL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_dayPNL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel11 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel11, 87);
lv_obj_set_height( ui_Panel11, 5);
lv_obj_set_x( ui_Panel11, -42 );
lv_obj_set_y( ui_Panel11, 1 );
lv_obj_set_align( ui_Panel11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x0B2B34), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 29 );
lv_obj_set_y( ui_Label1, 4 );
lv_label_set_text(ui_Label1,"Merry Christmass!!");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x6B5A6D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 250, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_1699707072);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_Image1, 14 );
lv_obj_set_y( ui_Image1, 73 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_secHEX = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_secHEX, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_secHEX, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_secHEX, -47 );
lv_obj_set_y( ui_secHEX, 61 );
lv_obj_set_align( ui_secHEX, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_secHEX,"0");
lv_obj_set_style_text_color(ui_secHEX, lv_color_hex(0x6B5A6D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_secHEX, 250, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_secHEX, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

}
